---
title: Blender - Make a marble
hero_image: images/banner.png
description: Make a marble shape in Blender and choose different colour effects
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: You will make
  - title: Step title
  - title: Step title
  - title: Step title
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
